namespace asa_server_controller.Models.Ini;

public sealed record GameUserSettingsFieldCatalogItem(
    string Key,
    string Section,
    string Type,
    bool IsServerManaged,
    bool Uncertain,
    string DefaultValue,
    bool IsUnsupported = false);

public static class GameUserSettingsCatalog
{
    public static IReadOnlyList<GameUserSettingsFieldCatalogItem> Fields { get; } =
    [
			  // Settings
        new("ActiveMods", "serverSettings", "textareainput", true, false, ""),
        new("ActiveTotalConversion", "serverSettings", "textinput", false, false, ""),
        new("AdminLogging", "serverSettings", "boolinput", false, false, "False"),
        new("AllowAnyoneBabyImprintCuddle", "serverSettings", "boolinput", false, false, "False"),
        new("AllowCrateSpawnsOnTopOfStructures", "serverSettings", "boolinput", false, false, "False"),
        new("AllowCryoFridgeOnSaddle", "serverSettings", "boolinput", false, true, "False"),
        new("AllowFlyingStaminaRecovery", "serverSettings", "boolinput", false, false, "False"),
        new("AllowHideDamageSourceFromLogs", "serverSettings", "boolinput", false, false, "True"),
        new("AllowIntegratedSPlusStructures", "serverSettings", "boolinput", false, false, "True"),
        new("AllowMultipleAttachedC4", "serverSettings", "boolinput", false, false, "False"),
        new("AllowRaidDinoFeeding", "serverSettings", "boolinput", false, true, "False"),
        new("AllowTekSuitPowersInGenesis", "serverSettings", "boolinput", false, false, "False"),
        new("AllowThirdPersonPlayer", "serverSettings", "boolinput", false, false, "True"),
        new("AlwaysAllowStructurePickup", "serverSettings", "boolinput", false, true, "False"),
        new("AlwaysNotifyPlayerLeft", "serverSettings", "boolinput", false, true, "False"),
        new("ArmadoggoDeathCooldown", "serverSettings", "floatinput", false, true, "3600"),
        new("AutoDestroyDecayedDinos", "serverSettings", "boolinput", false, true, "False"),
        new("AutoDestroyOldStructuresMultiplier", "serverSettings", "floatinput", false, false, "0.0"),
        new("AutoSavePeriodMinutes", "serverSettings", "floatinput", false, false, "15.0"),
        new("bForceCanRideFliers", "serverSettings", "boolinput", false, false, "False"),
        new("BanListURL", "serverSettings", "textinput", false, true, ""),
        new("ClampItemSpoilingTimes", "serverSettings", "boolinput", false, true, "False"),
        new("ClampItemStats", "serverSettings", "boolinput", false, false, "False"),
        new("ClampResourceHarvestDamage", "serverSettings", "boolinput", false, false, "False"),
        new("CosmeticWhitelistOverride", "serverSettings", "textinput", false, false, ""),
        new("CosmoWeaponAmmoReloadAmount", "serverSettings", "floatinput", false, true, "1"),
        new("CustomDynamicConfigUrl", "serverSettings", "textinput", false, false, ""),
        new("CustomLiveTuningUrl", "serverSettings", "textinput", false, false, ""),
        new("DayCycleSpeedScale", "serverSettings", "floatinput", false, false, "1.0"),
        new("DestroyTamesOverTheSoftTameLimit", "serverSettings", "boolinput", false, false, "False"),
        new("DestroyUnconnectedWaterPipes", "serverSettings", "boolinput", false, false, "False"),
        new("DifficultyOffset", "serverSettings", "floatinput", false, true, "1.0"),
        new("DinoCharacterFoodDrainMultiplier", "serverSettings", "floatinput", false, false, "1.0"),
        new("DinoCharacterHealthRecoveryMultiplier", "serverSettings", "floatinput", false, false, "1.0"),
        new("DinoCharacterStaminaDrainMultiplier", "serverSettings", "floatinput", false, true, "1.0"),
        new("DinoCountMultiplier", "serverSettings", "floatinput", false, false, "1.0"),
        new("DinoDamageMultiplier", "serverSettings", "floatinput", false, false, "1.0"),
        new("DinoResistanceMultiplier", "serverSettings", "floatinput", false, false, "1.0"),
        new("DisableCryopodEnemyCheck", "serverSettings", "boolinput", false, true, "False"),
        new("DisableCryopodFridgeRequirement", "serverSettings", "boolinput", false, true, "False"),
        new("DisableDinoDecayPvE", "serverSettings", "boolinput", false, false, "False"),
        new("DisableImprintDinoBuff", "serverSettings", "boolinput", false, false, "False"),
        new("DisablePvEGamma", "serverSettings", "boolinput", false, false, "False"),
        new("DisableStructureDecayPvE", "serverSettings", "boolinput", false, false, "False"),
        new("DisableWeatherFog", "serverSettings", "boolinput", false, false, "False"),
        new("DontAlwaysNotifyPlayerJoined", "serverSettings", "boolinput", false, true, "False"),
        new("EnableExtraStructurePreventionVolumes", "serverSettings", "boolinput", false, false, "False"),
        new("EnablePvPGamma", "serverSettings", "boolinput", false, true, "False"),
        new("ExtinctionEventTimeInterval", "serverSettings", "floatinput", false, true, "0"),
        new("FastDecayUnsnappedCoreStructures", "serverSettings", "boolinput", false, false, "False"),
        new("ForceAllStructureLocking", "serverSettings", "boolinput", false, true, "False"),
        new("ForceGachaUnhappyInCaves", "serverSettings", "boolinput", false, true, "True"),
        new("globalVoiceChat", "serverSettings", "boolinput", false, true, "False"),
        new("HarvestAmountMultiplier", "serverSettings", "floatinput", false, false, "1.0"),
        new("HarvestHealthMultiplier", "serverSettings", "floatinput", false, false, "1.0"),
        new("IgnoreLimitMaxStructuresInRangeTypeFlag", "serverSettings", "boolinput", false, false, "False"),
        new("ImplantSuicideCD", "serverSettings", "floatinput", false, false, "28800"),
        new("ItemStackSizeMultiplier", "serverSettings", "floatinput", false, false, "1.0"),
        new("KickIdlePlayersPeriod", "serverSettings", "floatinput", false, false, "3600.0"),
        new("MaxCosmoWeaponAmmo", "serverSettings", "floatinput", false, true, "-1"),
        new("MaxGateFrameOnSaddles", "serverSettings", "intinput", false, true, "0"),
        new("MaxHexagonsPerCharacter", "serverSettings", "intinput", false, true, "2000000000"),
        new("MaxPersonalTamedDinos", "serverSettings", "intinput", false, true, "0"),
        new("MaxPlatformSaddleStructureLimit", "serverSettings", "intinput", false, false, "75"),
        new("MaxTamedDinos", "serverSettings", "floatinput", false, false, "5000.0"),
        new("MaxTamedDinos_SoftTameLimit", "serverSettings", "intinput", false, false, "5000"),
        new("MaxTamedDinos_SoftTameLimit_CountdownForDeletionDuration", "serverSettings", "intinput", false, false, "604800"),
        new("MaxTrainCars", "serverSettings", "intinput", false, true, "8"),
        new("MaxTributeCharacters", "serverSettings", "intinput", false, true, "10"),
        new("MaxTributeDinos", "serverSettings", "intinput", false, true, "20"),
        new("MaxTributeItems", "serverSettings", "intinput", false, true, "50"),
        new("NightTimeSpeedScale", "serverSettings", "floatinput", false, false, "1.0"),
        new("NonPermanentDiseases", "serverSettings", "boolinput", false, true, "False"),
        new("NPCNetworkStasisRangeScalePlayerCountStart", "serverSettings", "intinput", false, false, "0"),
        new("NPCNetworkStasisRangeScalePlayerCountEnd", "serverSettings", "intinput", false, false, "0"),
        new("NPCNetworkStasisRangeScalePercentEnd", "serverSettings", "floatinput", false, false, "0.55"),
        new("OnlyAutoDestroyCoreStructures", "serverSettings", "boolinput", false, true, "False"),
        new("OnlyDecayUnsnappedCoreStructures", "serverSettings", "boolinput", false, false, "False"),
        new("OverrideOfficialDifficulty", "serverSettings", "floatinput", false, false, "0.0"),
        new("OverrideStructurePlatformPrevention", "serverSettings", "boolinput", false, false, "False"),
        new("OxygenSwimSpeedStatMultiplier", "serverSettings", "floatinput", false, false, "1.0"),
        new("PerPlatformMaxStructuresMultiplier", "serverSettings", "floatinput", false, true, "1.0"),
        new("PersonalTamedDinosSaddleStructureCost", "serverSettings", "intinput", false, false, "0"),
        new("PlatformSaddleBuildAreaBoundsMultiplier", "serverSettings", "floatinput", false, false, "1.0"),
        new("PlayerCharacterFoodDrainMultiplier", "serverSettings", "floatinput", false, false, "1.0"),
        new("PlayerCharacterHealthRecoveryMultiplier", "serverSettings", "floatinput", false, false, "1.0"),
        new("PlayerCharacterStaminaDrainMultiplier", "serverSettings", "floatinput", false, false, "1.0"),
        new("PlayerCharacterWaterDrainMultiplier", "serverSettings", "floatinput", false, false, "1.0"),
        new("PlayerDamageMultiplier", "serverSettings", "floatinput", false, false, "1.0"),
        new("PlayerResistanceMultiplier", "serverSettings", "floatinput", false, false, "1.0"),
        new("PreventDiseases", "serverSettings", "boolinput", false, false, "False"),
        new("PreventMateBoost", "serverSettings", "boolinput", false, false, "False"),
        new("PreventOfflinePvP", "serverSettings", "boolinput", false, false, "False"),
        new("PreventOfflinePvPInterval", "serverSettings", "floatinput", false, false, "0.0"),
        new("PreventSpawnAnimations", "serverSettings", "boolinput", false, false, "False"),
        new("PreventTribeAlliances", "serverSettings", "boolinput", false, false, "False"),
        new("ProximityChat", "serverSettings", "boolinput", false, true, "False"),
        new("PvEAllowStructuresAtSupplyDrops", "serverSettings", "boolinput", false, false, "False"),
        new("PvEStructureDecayPeriodMultiplier", "serverSettings", "floatinput", false, false, "1.0"),
        new("PvPDinoDecay", "serverSettings", "boolinput", false, false, "False"),
        new("PvPStructureDecay", "serverSettings", "boolinput", false, false, "False"),
        new("RandomSupplyCratePoints", "serverSettings", "boolinput", false, false, "False"),
        new("RCONEnabled", "serverSettings", "boolinput", false, false, "False"),
        new("RCONPort", "serverSettings", "intinput", true, false, "27020"),
        new("RCONServerGameLogBuffer", "serverSettings", "floatinput", false, false, "600.0"),
        new("ResourcesRespawnPeriodMultiplier", "serverSettings", "floatinput", false, false, "1.0"),
        new("ServerAdminPassword", "serverSettings", "textinput", false, false, ""),
        new("ServerAutoForceRespawnWildDinosInterval", "serverSettings", "floatinput", false, false, "0.0"),
        new("ServerCrosshair", "serverSettings", "boolinput", false, false, "True"),
        new("ServerForceNoHUD", "serverSettings", "boolinput", false, false, "False"),
        new("ServerHardcore", "serverSettings", "boolinput", false, false, "False"),
        new("ServerPassword", "serverSettings", "textinput", false, false, ""),
        new("serverPVE", "serverSettings", "boolinput", false, false, "False"),
        new("ShowFloatingDamageText", "serverSettings", "boolinput", false, false, "False"),
        new("ShowMapPlayerLocation", "serverSettings", "boolinput", false, false, "True"),
        new("SpectatorPassword", "serverSettings", "textinput", false, false, ""),
        new("StructureDamageMultiplier", "serverSettings", "floatinput", false, false, "1.0"),
        new("StructurePickupHoldDuration", "serverSettings", "floatinput", false, false, "0.5"),
        new("StructurePickupTimeAfterPlacement", "serverSettings", "floatinput", false, false, "30.0"),
        new("StructurePreventResourceRadiusMultiplier", "serverSettings", "floatinput", false, false, "1.0"),
        new("StructureResistanceMultiplier", "serverSettings", "floatinput", false, false, "1.0"),
        new("TamedDinoDamageMultiplier", "serverSettings", "floatinput", false, false, "1.0"),
        new("TamedDinoResistanceMultiplier", "serverSettings", "floatinput", false, false, "1.0"),
        new("TamingSpeedMultiplier", "serverSettings", "floatinput", false, false, "1.0"),
        new("TheMaxStructuresInRange", "serverSettings", "intinput", false, false, "10500"),
        new("TribeLogDestroyedEnemyStructures", "serverSettings", "boolinput", false, false, "False"),
        new("TribeNameChangeCooldown", "serverSettings", "floatinput", false, false, "15.0"),
        new("UseFjordurTraversalBuff", "serverSettings", "boolinput", false, false, "False"),
        new("UseOptimizedHarvestingHealth", "serverSettings", "boolinput", false, false, "False"),
        new("XPMultiplier", "serverSettings", "floatinput", false, false, "1.0"),
        new("YoungIceFoxDeathCooldown", "serverSettings", "floatinput", false, false, "3600"),
				// CrossARK Transfers
        new("CrossARKAllowForeignDinoDownloads", "serverSettings", "boolinput", false, false, "False"),
        new("MinimumDinoReuploadInterval", "serverSettings", "floatinput", false, false, "0.0"),
        new("noTributeDownloads", "serverSettings", "boolinput", false, false, "False"),
        new("PreventDownloadDinos", "serverSettings", "boolinput", false, false, "False"),
        new("PreventDownloadItems", "serverSettings", "boolinput", false, false, "False"),
        new("PreventDownloadSurvivors", "serverSettings", "boolinput", false, false, "False"),
        new("PreventUploadDinos", "serverSettings", "boolinput", false, false, "False"),
        new("PreventUploadItems", "serverSettings", "boolinput", false, false, "False"),
        new("PreventUploadSurvivors", "serverSettings", "boolinput", false, false, "False"),
        new("TributeCharacterExpirationSeconds", "serverSettings", "intinput", false, false, "0"),
        new("TributeDinoExpirationSeconds", "serverSettings", "intinput", false, false, "86400"),
        new("TributeItemExpirationSeconds", "serverSettings", "intinput", false, false, "86400"),
				// Cryo Sickness and Cryopod Nerf
        new("EnableCryoSicknessPVE", "cryoSickness", "boolinput", false, false, "False"),
        new("EnableCryopodNerf", "cryoSickness", "boolinput", false, false, "False"),
        new("CryopodNerfDamageMult", "cryoSickness", "floatinput", false, false, "0.01"),
        new("CryopodNerfDuration", "cryoSickness", "intinput", false, false, "0"),
        new("CryopodNerfIncomingDamageMultPercent", "cryoSickness", "floatinput", false, false, "0.0"),
        // Text filtering
        new("BadWordListURL", "serverSettings", "textinput", false, false, ""),
        new("BadWordWhiteListURL", "serverSettings", "textinput", false, false, ""),
        new("bFilterChat", "serverSettings", "boolinput", false, true, "False"),
        new("bFilterCharacterNames", "serverSettings", "boolinput", false, true, "False"),
        new("bFilterTribeNames", "serverSettings", "boolinput", false, true, "False"),
				// Tech bunker
        new("LimitBunkersPerTribe", "serverSettings", "boolinput", false, false, "True"),
        new("LimitBunkersPerTribeNum", "serverSettings", "intinput", false, false, "3"),
        new("AllowBunkersInPreventionZones", "serverSettings", "boolinput", false, false, "False"),
        new("AllowRidingDinosInsideBunkers", "serverSettings", "boolinput", false, false, "True"),
        new("AllowBunkerModulesAboveGround", "serverSettings", "boolinput", false, false, "False"),
        new("AllowDinoAIInsideBunkers", "serverSettings", "boolinput", false, false, "True"),
        new("AllowBunkerModulesInPreventionZones", "serverSettings", "boolinput", false, false, "False"),
        new("MinDistanceBetweenBunkers", "serverSettings", "floatinput", false, false, "3000.0"),
        new("EnemyAccessBunkerHPThreshold", "serverSettings", "floatinput", false, false, "0.25"),
        new("BunkerUnderHPThresholdDmgMultiplier", "serverSettings", "floatinput", false, false, "0.05"),
				// CryoHospital
				new("CryoHospitalHoursToRegenHP", "serverSettings", "floatinput", false, false, "1.0"),
        new("CryoHospitalHoursToRegenFood", "serverSettings", "floatinput", false, false, "24.0"),
        new("CryoHospitalHoursToDrainTorpor", "serverSettings", "floatinput", false, false, "1.0"),
        new("CryoHospitalMatingCooldownReduction", "serverSettings", "floatinput", false, false, "2.0"),
				// Bloodforge
				new("BloodforgeReinforceExtraDurability", "serverSettings", "floatinput", false, false, "0.3"),
        new("BloodforgeReinforceResourceCostMultiplier", "serverSettings", "floatinput", false, false, "3.0"),
        new("BloodforgeReinforceSpeedMultiplier", "serverSettings", "floatinput", false, false, "0.1"),
				// Outposts
        new("MaxActiveOutposts", "serverSettings", "intinput", false, false, "0"),
        new("MaxActiveResourceCaches", "serverSettings", "intinput", false, false, "0"),
        new("MaxActiveCityOutposts", "serverSettings", "intinput", false, false, "0"),
        // Undocumented options
        new("AdminListURL", "serverSettings", "textinput", false, false, ""),
        new("AutoRestartIntervalSeconds", "serverSettings", "floatinput", false, true, "Unknown"),
        new("ChatLogFileSplitIntervalSeconds", "serverSettings", "intinput", false, true, "86400"),
        new("ChatLogFlushIntervalSeconds", "serverSettings", "intinput", false, true, "86400"),
        new("ChatLogMaxAgeInDays", "serverSettings", "intinput", false, true, "5"),
        new("DontRestoreBackup", "serverSettings", "boolinput", false, true, "False"),
        new("EnableAFKKickPlayerCountPercent", "serverSettings", "floatinput", false, true, "0.0"),
        new("EnableMeshBitingProtection", "serverSettings", "boolinput", false, true, "True"),
        new("FreezeReaperPregnancy", "serverSettings", "boolinput", false, true, "False", true),
        new("LogChatMessages", "serverSettings", "boolinput", false, true, "False", true),
        new("MaxStructuresInSmallRadius", "serverSettings", "intinput", false, true, "0"),
        new("MaxStructuresToProcess", "serverSettings", "intinput", false, true, "0"),
        new("PreventOutOfTribePinCodeUse", "serverSettings", "boolinput", false, true, "False"),
        new("RadiusStructuresInSmallRadius", "serverSettings", "floatinput", false, true, "0.0"),
        new("ServerEnableMeshChecking", "serverSettings", "boolinput", false, true, "False"),
        new("TribeMergeAllowed", "serverSettings", "boolinput", false, true, "True", true),
        new("TribeMergeCooldown", "serverSettings", "floatinput", false, true, "0.0", true),
        new("UpdateAllowedCheatersInterval", "serverSettings", "floatinput", false, true, "600.0"),
        new("UseCharacterTracker", "serverSettings", "boolinput", false, true, "False"),
        new("UseExclusiveList", "serverSettings", "boolinput", false, true, "False"),
        // Session settings
        new("SessionName", "sessionSettings", "textinput", true, false, "ARK #123456"),
        new("Port", "sessionSettings", "intinput", true, false, "7777"),
        new("QueryPort", "sessionSettings", "intinput", true, true, "27015"),
        new("MultiHome", "sessionSettings", "boolinput", false, false, "False"),
        // Multihome
        new("MultiHomeAddress", "multiHome", "textinput", false, true, ""),
        // Ragnarok
        new("AllowMultipleTamedUnicorns", "ragnarok", "boolinput", false, true, "False"),
        new("EnableVolcano", "ragnarok", "boolinput", false, true, "True"),
        new("UnicornSpawnInterval", "ragnarok", "intinput", false, true, "24"),
        new("VolcanoIntensity", "ragnarok", "floatinput", false, true, "1"),
        new("VolcanoInterval", "ragnarok", "intinput", false, true, "0"),
				// Message of the day
        new("Duration", "messageOfTheDay", "intinput", false, false, "20"),
        new("Message", "messageOfTheDay", "textareainput", false, false, ""),
    ];
}
